CaptureBadgeEntrances = {
    "@Forest Chest Game/Entrance",
    "@Lumberjack House/Entrance",
    "@Kakariko Fortune Teller/Entrance",
    "@Left Snitch House/Entrance",
    "@Blind's House Entrance/Entrance",
    "@Elder Left Door/Entrance",
    "@Elder Right Door/Entrance",
    "@Right Snitch House/Entrance",
    "@Chicken House Entrance/Entrance",
    "@Sick Kid Entrance/Entrance",
    "@Grass House/Entrance",
    "@Bomb Hut/Entrance",
    "@Kakariko Shop/Entrance",
    "@Tavern Entrance/Entrance",
    "@Smith's House/Entrance",
    "@Quarreling Brothers Left/Entrance",
    "@Quarreling Brothers Right/Entrance",
    "@Library Entrance/Entrance",
    "@Kakariko Chest Game/Entrance",
    "@North Bonk Rocks/Entrance",
    "@Old Man Home/Entrance",
    "@Graveyard Ledge Cave/Entrance",
    "@King's Tomb Grave/Entrance",
    "@Castle Left Entrance/Entrance",
    "@Agahnim's Tower Entrance/Entrance",
    "@Castle Right Entrance/Entrance",
    "@Castle Main Entrance/Entrance",
    "@Witch's Hut/Entrance",
    "@Sahasrala's Hut Entrance/Entrance",
    "@Eastern Palace Entrance/Entrance",
    "@Trees Fairy Cave/Entrance",
    "@Long Fairy Cave/Entrance",
    "@Desert Back Entrance/Entrance",
    "@Desert Left Entrance/Entrance",
    "@Desert Front Entrance/Entrance",
    "@Desert Right Entrance/Entrance",
    "@Checkerboard Cave Entrance/Entrance",
    "@Aginah's Cave Entrance/Entrance",
    "@Cave 45 Entrance/Entrance",
    "@Desert Fairy Cave/Entrance",
    "@Fifty Rupee Cave/Entrance",
    "@Dam Entrance/Entrance",
    "@Central Bonk Rocks/Entrance",
    "@Link's House Entrance/Entrance",
    "@Hype Fairy Cave/Entrance",
    "@Lake Fortune Teller/Entrance",
    "@Mini Moldorm Cave Entrance/Entrance",
    "@Lake Shop/Entrance",
    "@Upgrade Fairy/Entrance",
    "@Ice Rod Cave Entrance/Entrance",
    "@Cold Bee Cave/Entrance",
    "@Twenty Rupee Cave/Entrance",
    "@Death Mountain Descent Front/Entrance",
    "@Death Mountain Descent Back/Entrance",
    "@Death Mountain Entry Cave/Entrance",
    "@Death Mountain Entry Back/Entrance",
    "@Tower of Hera Entrance/Entrance",
    "@Spectacle Rock Top/Entrance",
    "@Spectacle Rock Left/Entrance",
    "@Spectacle Rock Bottom/Entrance",
    "@Old Man Back Door/Entrance",
    "@Paradox Cave Top/Entrance",
    "@Spiral Cave Top/Entrance",
    "@Mimic Cave Entrance/Entrance",
    "@Fairy Ascension Top/Entrance",
    "@Spiral Cave Bottom/Entrance",
    "@Fairy Ascension Bottom/Entrance",
    "@Hookshot Fairy Cave/Entrance",
    "@Paradox Cave Bottom/Entrance",
    "@Waterfall Fairy Cave/Entrance",
    "@Paradox Cave Middle/Entrance",
    "@Skull Woods Back/Entrance",
    "@Dark Lumberjack/Entrance",
    "@Dark Chapel/Entrance",
    "@Shield Shop/Entrance",
    "@Village of Outkasts Fortune Teller/Entrance",
    "@Chest Game Entrance/Entrance",
    "@Thieves Town Entrance/Entrance",
    "@C-Shaped House Entrance/Entrance",
    "@Hammer House/Entrance",
    "@Brewery Entrance/Entrance",
    "@Hammer Pegs Cave/Entrance",
    "@Archery Game/Entrance",
    "@Pyramid Fairy Cave/Entrance",
    "@Dark Witch's Hut/Entrance",
    "@Dark Sahasrahla/Entrance",
    "@Palace of Darkness Entrance/Entrance",
    "@Dark Trees Fairy/Entrance",
    "@East Storyteller Cave/Entrance",
    "@Mire Shed Cave/Entrance",
    "@Misery Mire Entrance/Entrance",
    "@Mire Fairy/Entrance",
    "@Mire Hint Cave/Entrance",
    "@Swamp Palace Entrance/Entrance",
    "@Dark Bonk Rocks/Entrance",
    "@Bomb Shop/Entrance",
    "@Hype Cave Entrance/Entrance",
    "@Dark Lake Shop/Entrance",
    "@Ice Palace Entrance/Entrance",
    "@Dark Lake Hylia Fairy/Entrance",
    "@Hamburger Helper Cave/Entrance",
    "@Spike Hint Cave/Entrance",
    "@Bumper Cave Top/Entrance",
    "@Bumper Cave Bottom/Entrance",
    "@Dark Mountain Fairy/Entrance",
    "@Spike Cave Entrance/Entrance",
    "@Ganon's Tower Entrance/Entrance",
    "@Hookshot Cave Island/Entrance",
    "@Hookshot Cave Entrance/Entrance",
    "@Superbunny Cave Top/Entrance",
    "@Turtle Ledge Left Entrance/Entrance",
    "@Turtle Ledge Right Entrance/Entrance",
    "@Turtle Laser Bridge Entrance/Entrance",
    "@Superbunny Cave Bottom/Entrance",
    "@Dark Death Mountain Shop/Entrance",
    "@Turtle Rock Entrance/Entrance"
}

CaptureBadgeDropdowns = {
    "@Forest Hideout Drop/Dropdown",
    "@Lumberjack Tree/Dropdown",
    "@Kakariko Well Drop/Dropdown",
    "@Magic Bat Drop/Dropdown",
    "@Secret Passage Drop/Dropdown",
    "@Useless Fairy Drop/Dropdown",
    "@Sanctuary Grave/Dropdown",
    "@Castle Hole/Dropdown",
    "@Pyramid Hole/Dropdown"
}

CaptureBadgeInsanity = {
    "@Forest Hideout Exit/Entrance",
    "@Lumberjack Tree Exit/Entrance",
    "@Kakariko Well Exit/Entrance",
    "@Magic Bat Exit/Entrance",
    "@Sanctuary Exit/Entrance",
    "@Useless Fairy Exit/Entrance",
    "@Secret Passage Exit/Entrance",
    "@Pyramid Hole Exit/Entrance",
    "@Castle Hole Exit/Entrance",
    "@Skull Woods Back South/Entrance",
    "@Skull Woods Front Right/Entrance",
    "@Skull Woods Front Left/Entrance",
    "@Skull Woods Back Drop/Dropdown",
    "@Skull Woods Big Chest Drop/Dropdown",
    "@Skull Woods Front Right Drop/Dropdown",
    "@Skull Woods Front Left Drop/Dropdown"
}

CaptureBadgeOverworld = {
    "@Master Sword Pedestal/Pedestal",
    "@Mushroom Spot/Shroom",
    "@Race Game/Take This Trash",
    "@Desert Ledge/Ledge",
    "@Bombos Tablet/Tablet",
    "@Lake Hylia Island/Island",
    "@Ether Tablet/Tablet",
    "@Spectacle Rock/Up On Top",
    "@Floating Island/Island",
    "@Zora's Domain/Ledge",
    "@Bumper Ledge/Ledge"
}

CaptureBadgeUnderworld = {
    "@Forest Hideout/Stash",
    "@Lumberjack Cave/Cave",
    "@Library/On The Shelf",
    "@Cave 45/Circle of Bushes"
}

DungeonList = { "hc", "ep", "dp", "at", "sp", "pod", "mm", "sw", "ip", "toh", "tt", "tr", "gt" }

DungeonData = { --dungeonPrefix = location header, chest keys, key drops, dungeon order index
    ["hc"] = { "@Hyrule Castle & Escape", 1, 3, 0 },
    ["ep"] = { "@Eastern Palace", 0, 2, 1 },
    ["dp"] = { "@Desert Palace", 1, 3, 2 },
    ["at"] = { "@Agahnim's Tower", 2, 2, 4 },
    ["sp"] = { "@Swamp Palace", 1, 5, 6 },
    ["pod"] = { "@Palace of Darkness", 6, 0, 5 },
    ["mm"] = { "@Misery Mire", 3, 3, 10 },
    ["sw"] = { "@Skull Woods", 3, 2, 7 },
    ["ip"] = { "@Ice Palace", 2, 4, 9 },
    ["toh"] = { "@Tower of Hera", 1, 0, 3 },
    ["tt"] = { "@Thieves Town", 1, 2, 8 },
    ["tr"] = { "@Turtle Rock", 4, 2, 11 },
    ["gt"] = { "@Ganon's Tower", 4, 4, 12 }
}

DungeonIdMap = {
    [0] = "hc", --sewer
    [2] = "hc",
    [4] = "ep",
    [6] = "dp",
    [8] = "at",
    [10] = "sp",
    [12] = "pod",
    [14] = "mm",
    [16] = "sw",
    [18] = "ip",
    [20] = "toh",
    [22] = "tt",
    [24] = "tr",
    [26] = "gt",
    [255] = "OW"
}

OverworldIdRegionMap = {
    [0x02] = "light_world", [0x03] = "dm_west_bottom",
    [0x11] = "light_world", [0x13] = "light_world", [0x15] = "light_world", [0x16] = "lw_witch",
    [0x22] = "light_world", [0x1e] = "light_world",
    [0x28] = "light_world", [0x29] = "light_world", [0x2b] = "light_world", [0x2c] = "light_world",
    [0x32] = "light_world", [0x34] = "light_world", [0x37] = "light_world",
    [0x3a] = "light_world", [0x3b] = "light_world",
    [0x42] = "dw_west", [0x43] = "ddm_west", [0x47] = "ddm_top",
    [0x51] = "dw_west", [0x53] = "dw_west", [0x56] = "dw_witch",
    [0x5a] = "dw_west", [0x5b] = "dw_east", [0x5e] = "dw_east",
    [0x69] = "dw_south", [0x6b] = "dw_south", [0x6c] = "dw_south",
    [0x70] = "mire_area", [0x74] = "dw_south", [0x77] = "dw_southeast",
    [0x7b] = "dw_south"
}
                
